language: node_js

node_js:
    - "node"

sudo: false

git:
    submodules: false

before_script:
    - npm install

script:
    - npm run ci

after_success:
    - npm run report-coveralls
    - npm run report-codecov
